name: Deploy frontend

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on production server
        run: |
          bash ~/node_coap_server/deploy.sh
